export const heading: string
export const headingWithTopMargin: string
export const subHeading: string
export const title: string
export const codeHeading: string
export const h1: string
export const h5: string
export const typeText: string
export const note: string
export const codeBlock: string
export const error: string
export const questionTitle: string
