export const logo: string
export const desktopLogo: string
export const head: string
export const videoHeading: string
export const toggleGroup: string
export const video: string
export const videoWrapperShow: string
export const videoWrapperHide: string
export const logoHeading: string
