export const iconGroup: string
export const icon: string
export const actionButtonGroup: string
export const gitHubButtonWrap: string
export const iconWrapper: string
export const langSelect: string
export const lightLangSelect: string
export const lightActionButtonWrapper: string
export const mobileMenu: string
export const darkActionButtonGroup: string
